const productosData = {
    productos: [
        {
            nombre: "Arnés Strap-on con Doble Vibrador",
            precio: 45,
            imagen: "imagen/arnes.jpg",
            categorias: ["ropa", "accesorios", "vibradores"],
            disponible: true,
            material: "Silicona",
            dimensiones: "17.5 cm y 12.5 cm",
            diametro: "2.2 cm y 3.5 cm",
            incluye: "Dildos intercambiables",
            color: "Morado",
            fechaAgregado: "2026-03-12",
            oferta: false
        },
        {
            nombre: "Vibrador Succionador de Clitorís y Estimulador de Punto G (Control por APP)",
            precio: 45,
            imagen: "imagen/vibrador.jpg",
            categorias: ["vibradores"],
            disponible: true,
            material: "Silicona ABS",
            largo: "11 cm",
            diametro: "3.4 cm",
            bateria: "Carga USB Magnética",
            vibracion: "9 modos",
            succion: "9 modos",
            color: "Rosado, Morado",
            fechaAgregado: "2026-03-12",
            oferta: false
        },
        {
            nombre: "Estimulador Prostático Masculino",
            precio: 65,
            imagen: "imagen/estimuladorhomb.jpg",
            categorias: ["vibradores", "hombre"],
            disponible: true,
            largo: "9.3 cm",
            diametro: "2 cm",
            material: "Silicona ABS",
            bateria: "1 Pila AAA (No incluida)",
            color: "Morado",
            vibracion: "10 Formas de Vibración",
            fechaAgregado: "2026-03-10",
            oferta: false
        },
        {
            nombre: "Vibrador Vaginal y Punto G (Control por APP)",
            precio: 30,
            imagen: "imagen/vibraVPG.jpg",
            categorias: ["vibradores"],
            disponible: true,
            largo: "8 cm",
            diametro: "3.2 cm",
            material: "Silicona ABS",
            bateria: "Carga USB",
            color: "Rosado, Morado",
            vibracion: "9 Modos",
            fechaAgregado: "2026-03-10",
            oferta: false
        },
        {
            nombre: "Vibrador Doble Strap-on Sin Correa",
            precio: 65,
            imagen: "imagen/vibraDS.jpg",
            categorias: ["vibradores"],
            disponible: true,
            largo: "23 cm y 12 cm",
            diametro: "4 cm",
            material: "Silicona ABS",
            bateria: "Carga USB",
            color: "Morado",
            vibracion: "10 Modos",
            fechaAgregado: "2026-03-10",
            oferta: false
        },        
        {
            nombre: "Arnés Strap-on de Doble Vibrador",
            precio: 50,
            imagen: "imagen/arnes2.jpg",
            categorias: ["vibradores", "ropa", "accesorios"],
            disponible: true,
            largo: "18.5 cm y 13 cm",
            diametro: "3.5 cm y 2.5 cm'",
            material: "Silicona ABS",
            bateria: "3 Pilas AAA (No incluidas)",
            color: "Negro, Morado",
            vibracion: "Ascendente",
            fechaAgregado: "2026-03-10",
            oferta: false
        },        
        {
            nombre: "Dildo Realista Con Ventosa (Mando Alámbrico)",
            precio: 35,
            imagen: "imagen/dildo.jpg",
            categorias: ["vibradores", "dildos"],
            disponible: true,
            largo: "18 cm",
            diametro: "3.5 cm'",
            material: "Silicona ABS",
            bateria: "2 Pilas AAA (No incluidas)",
            color: "Piel",
            vibracion: "10 Modos",
            fechaAgregado: "2026-03-10",
            oferta: false
        },
        {
            nombre: "Lencería Sexy de Hombre",
            precio: 13,
            imagen: "imagen/lenceH.jpg",
            categorias: ["ropa", "lencería", "lencería hombre", "hombre"],
            disponible: true,
            talla: "Talla Única",
            fechaAgregado: "2026-03-10",
            oferta: false
        },
        {
            nombre: "Dildo Realista Telescópico 3 en 1 (Mando inalámbrico)",
            precio: 45,
            imagen: "imagen/dildo2.jpg",
            categorias: ["vibradores", "dildos"],
            disponible: true,
            largo: "19 cm",
            diametro: "3.5 cm'",
            material: "Silicona ABS",
            bateria: "Carga USB Magnética",
            color: "Piel",
            vibracion: "10 Modos",
            empuje: "10 Modos",
            fechaAgregado: "2026-03-10",
            oferta: false
        },
        {
            nombre: "Arnés Strap-on con Dildo de Ventosa",
            precio: 45,
            imagen: "imagen/arnes3.jpg",
            categorias: ["ropa", "accesorios"],
            disponible: true,
            largo: "21.5 cm",
            diametro: "3.8 cm",
            material: "Silicona",
            color: "Marron, Morado",
            fechaAgregado: "2026-03-10",
            oferta: false
        },
        {
            nombre: "Vibrador dr Braga Magnético (Control por APP)",
            precio: 35,
            imagen: "imagen/vibraBrag.jpg",
            categorias: ["vibradores", "accesorios"],
            disponible: true,
            largo: "9 cm",
            material: "Silicona ABS",
            bateria: "Carga USB Magnética",
            color: "Verde",
            vibracion: "9 Modos",
            fechaAgregado: "2026-03-10",
            oferta: false
        },
        {
            nombre: "Dildo de Ventosa Realista",
            precio: 30,
            imagen: "imagen/dildo4.jpg",
            categorias: ["dildos"],
            disponible: true,
            largo: "18 cm",
            diametro: "3.5 cm",
            material: "Silicona Médica",
            color: "Piel",
            fechaAgregado: "2026-03-10",
            oferta: false
        },
        {
            nombre: "Dildo de Ventosa Realista XL",
            precio: 45,
            imagen: "imagen/dildo3.jpg",
            categorias: ["dildos"],
            disponible: true,
            largo: "26 cm",
            diametro: "4.5 cm",
            material: "Silicona Médica",
            color: "Piel",
            fechaAgregado: "2026-03-10",
            oferta: false
        },
        {
            nombre: "Dildo de Ventosa Realista XS",
            precio: 25,
            imagen: "imagen/dildo5.jpg",
            categorias: ["dildos"],
            disponible: true,
            largo: "16 cm",
            diametro: "3 cm",
            material: "Silicona",
            color: "Rosado, Blanco, Marron Claro",
            fechaAgregado: "2026-03-10",
            oferta: false
        },
        {
            nombre: "Lencería Shein #01",
            precio: 13,
            imagen: "imagen/L3.jpg",
            categorias: ["lencería","ropa", "lencería de mujer"],
            disponible: true,
            talla: "S, M, L",
            color: "Negro",
            fechaAgregado: "2026-03-10",
            oferta: false
        },
        {
            nombre: "Lencería Shein #02",
            precio: 13,
            imagen: "imagen/L6.jpg",
            categorias: ["lencería","ropa", "lencería de mujer"],
            disponible: true,
            talla: "S, M, L",
            color: "Negro",
            fechaAgregado: "2026-03-10",
            oferta: false
        },
        {
            nombre: "Lencería Shein #03",
            precio: 13,
            imagen: "imagen/L9.jpg",
            categorias: ["lencería","ropa", "lencería de mujer"],
            disponible: true,
            talla: "S, M, L",
            color: "Negro, Rojo",
            fechaAgregado: "2026-03-10",
            oferta: false
        },
        {
            nombre: "Lencería Shein #04",
            precio: 13,
            imagen: "imagen/L13.jpg",
            categorias: ["lencería","ropa", "lencería de mujer"],
            disponible: true,
            talla: "S, L",
            color: "Negro y Rojo",
            fechaAgregado: "2026-03-10",
            oferta: false
        },
        {
            nombre: "Lencería Shein #05",
            precio: 13,
            imagen: "imagen/L14.jpg",
            categorias: ["lencería","ropa", "lencería de mujer"],
            disponible: true,
            talla: "S, M, L",
            color: "Negro, Rojo",
            fechaAgregado: "2026-03-10",
            oferta: false
        },
        {
            nombre: "Lencería Shein #06",
            precio: 13,
            imagen: "imagen/L15.jpg",
            categorias: ["lencería","ropa", "lencería de mujer"],
            disponible: true,
            talla: "Unitalla",
            color: "Negro, Rojo",
            fechaAgregado: "2026-03-10",
            oferta: false
        },
        {
            nombre: "Lencería Shein #07",
            precio: 13,
            imagen: "imagen/L16.jpg",
            categorias: ["lencería","ropa", "lencería de mujer"],
            disponible: true,
            talla: "L",
            fechaAgregado: "2026-03-10",
            oferta: false
        },
        {
            nombre: "Lencería Shein #08",
            precio: 13,
            imagen: "imagen/L17.jpg",
            categorias: ["lencería","ropa", "lencería de mujer"],
            disponible: true,
            talla: "S, M, L",
            color: "Verde",
            fechaAgregado: "2026-03-10",
            oferta: false
        },
        {
            nombre: "Lencería Shein #09",
            precio: 13,
            imagen: "imagen/L18.jpg",
            categorias: ["lencería","ropa", "lencería de mujer"],
            disponible: true,
            talla: "L",
            fechaAgregado: "2026-03-10",
            oferta: false
        },
        {
            nombre: "Plug Dilatador Anal Metálico",
            precio: 20,
            imagen: "imagen/plug.jpg",
            categorias: ["plugs", "anal"],
            disponible: true,
            largo: "7 cm",
            diametro: "2.8 cm",
            material: "Metal",
            color: "Rojo",
            fechaAgregado: "2026-03-10",
            oferta: false
        },
        {
            nombre: "Funda Extensora y Engrosadora de Pene",
            precio: 10,
            imagen: "imagen/funda.jpg",
            categorias: ["fundas", "hombre"],
            disponible: true,
            largo: "14 cm",
            diametro: "5 cm",
            material: "Silicona",
            color: "Transparente",
            fechaAgregado: "2026-03-10",
            oferta: false
        },
        {
            nombre: "Plugs Dilatadores Anales de Silicona",
            precio: 10,
            imagen: "imagen/plug2.jpg",
            categorias: ["plugs", "anal"],
            disponible: true,
            largo: "8 cm - 12 cm",
            diametro: "1.3 cm - 3.6 cm",
            material: "Silicona",
            color: "Rosado, Negro",
            fechaAgregado: "2026-03-10",
            oferta: false
        },
        {
            nombre: "Lengua Vibradora Estimuladora de Clítoris",
            precio: 35,
            imagen: "imagen/lengua.jpg",
            categorias: ["vibradores"],
            disponible: true,
            largo: "10.5 cm",
            diametro: "3 cm",
            material: "Silicona",
            bateria: "Carga USB",
            color: "Rosado",
            vibracion: "10 Modos",
            fechaAgregado: "2026-03-10",
            oferta: false
        },
        {
            nombre: "Lengua Vibradora",
            precio: 30,
            imagen: "imagen/lengua2.jpg",
            categorias: ["vibradores"],
            disponible: true,
            largo: "10 cm",
            diametro: "3.3 cm",
            material: "Silicona Médica Suave",
            bateria: "2 Pilas AAA (No Incluidas)",
            color: "Piel",
            vibracion: "10 Frecuencias",
            fechaAgregado: "2026-03-10",
            oferta: false
        },
        {
            nombre: "Consolador Vibrador Estimulador de Punto G",
            precio: 40,
            imagen: "imagen/consola.jpg",
            categorias: ["vibradores", "consolador"],
            disponible: true,
            largo: "14 cm (Introducibles)",
            diametro: "3 cm",
            material: "Silicona ABS",
            bateria: "Carga USB",
            color: "Rosado",
            vibracion: "10 Frecuencias",
            fechaAgregado: "2026-03-10",
            oferta: false
        },
        {
            nombre: "Consolador Vibrador de Conejito (360° Giratorio)",
            precio: 50,
            imagen: "imagen/consola2.jpg",
            categorias: ["vibradores", "consolador"],
            disponible: true,
            largo: "11 cm",
            diametro: "3 cm",
            material: "Silicona Suave",
            bateria: "Carga USB",
            color: "Amarillo, Morado",
            vibracion: "10 Frecuencias",
            fechaAgregado: "2026-03-10",
            oferta: false
        },
        {
            nombre: "Consolador Vibrador Gelly",
            precio: 30,
            imagen: "imagen/consola3.jpg",
            categorias: ["vibradores", "consolador"],
            disponible: true,
            largo: "14 cm",
            diametro: "3 cm",
            material: "Silicona Suave",
            bateria: "2 Pilas AAA (No Incluidas)",
            color: "Rosado, Morado, Azul, Rojo",
            vibracion: "Estandar Ascendente",
            fechaAgregado: "2026-03-10",
            oferta: false
        },
        {
            nombre: "Vibrador Masajeador Multifuncional",
            precio: 35,
            imagen: "imagen/masaje.jpg",
            categorias: ["vibradores", "masajeador"],
            disponible: true,
            largo: "19.5 cm",
            diametro: "4 cm",
            material: "Silicona ABS",
            bateria: "Carga USB",
            color: "Morado",
            vibracion: "20 Frecuencias",
            fechaAgregado: "2026-03-10",
            oferta: false
        },
        {
            nombre: "Huevo Vibrador",
            precio: 20,
            imagen: "imagen/huevo.jpg",
            categorias: ["vibradores"],
            disponible: true,
            largo: "5 cm",
            diametro: "2.4 cm",
            material: "Silicona y Plástico",
            bateria: "2 Pilas AA (No Incluidas)",
            color: "Rosado",
            vibracion: "Ascendente",
            fechaAgregado: "2026-03-10",
            oferta: false
        },
        
    ]
};

const IMAGEN_DEFAULT = "img/default-product.jpg";
